import React, { useState, useEffect } from "react";
import axios from "axios";
import io from "socket.io-client";
import {
  Bell,
  Flame,
  AlertTriangle,
  Car,
  Clock,
  CheckCircle2,
  Filter,
  RotateCcw,
  ShieldAlert,
  ChevronRight,
  Video
} from "lucide-react";

const BACKEND_URL = "http://localhost:5000";

export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [filter, setFilter] = useState("ALL"); // 'ALL' | 'ACTIVE' | 'RESOLVED'
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAlerts();

    // Connect to WebSockets to stream incoming Module 4 alerts in real-time
    const socket = io(BACKEND_URL);

    socket.on("congestion_alert", (newAlert) => {
      setAlerts((prev) => [newAlert, ...prev]);
    });

    return () => socket.disconnect();
  }, []);

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${BACKEND_URL}/api/congestion/active`);
      if (res.data?.status === "success") {
        setAlerts(res.data.data || []);
      }
    } catch (err) {
      console.error("Failed to load alerts feed:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleResolve = async (id) => {
    try {
      await axios.patch(`${BACKEND_URL}/api/congestion/resolve/${id}`);
      setAlerts((prev) =>
        prev.map((item) =>
          item._id === id ? { ...item, resolved: true } : item
        )
      );
    } catch (err) {
      console.error("Failed to resolve alert:", err);
    }
  };

  const activeCount = alerts.filter((a) => !a.resolved).length;
  const resolvedCount = alerts.filter((a) => a.resolved).length;

  const filteredAlerts = alerts.filter((item) => {
    if (filter === "ACTIVE") return !item.resolved;
    if (filter === "RESOLVED") return item.resolved;
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-bold text-slate-900">System Alerts & Incidents</h1>
            <span className="inline-flex items-center gap-1.5 px-3 py-0.5 rounded-full text-xs font-semibold bg-rose-50 text-rose-700 border border-rose-200">
              <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" />
              {activeCount} Active Gridlocks
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Automated notifications generated by Module 4 Congestion Kinematics and Multi-Camera Re-ID
          </p>
        </div>

        <button
          onClick={fetchAlerts}
          className="inline-flex items-center gap-2 px-3.5 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
        >
          <RotateCcw className="w-3.5 h-3.5" />
          Refresh Feed
        </button>
      </div>

      {/* Main Alert List Container */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        {/* Filter Navigation Bar */}
        <div className="p-5 border-b border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-slate-50/50">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-slate-700" />
            <h2 className="text-sm font-bold text-slate-900">Real-Time Incident Records</h2>
            <span className="text-xs text-slate-400">({filteredAlerts.length} total)</span>
          </div>

          <div className="flex items-center gap-1 bg-slate-200/70 p-1 rounded-xl">
            <button
              onClick={() => setFilter("ALL")}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all ${
                filter === "ALL"
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              All Incidents ({alerts.length})
            </button>
            <button
              onClick={() => setFilter("ACTIVE")}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all ${
                filter === "ACTIVE"
                  ? "bg-rose-600 text-white shadow-sm"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              Active ({activeCount})
            </button>
            <button
              onClick={() => setFilter("RESOLVED")}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all ${
                filter === "RESOLVED"
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              Resolved ({resolvedCount})
            </button>
          </div>
        </div>

        {/* Incidents Feed */}
        <div className="divide-y divide-slate-100">
          {loading ? (
            <div className="py-16 text-center text-xs text-slate-400">
              Loading real-time incidents from database...
            </div>
          ) : filteredAlerts.length === 0 ? (
            <div className="py-16 text-center">
              <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto mb-2 opacity-80" />
              <p className="text-sm font-semibold text-slate-700">No Incidents Found</p>
              <p className="text-xs text-slate-400 mt-0.5">
                No alerts logged under the "{filter}" filter. Run a video in Traffic & Congestion to trigger an alert.
              </p>
            </div>
          ) : (
            filteredAlerts.map((alert) => (
              <div
                key={alert._id || Math.random()}
                className={`p-5 transition-colors flex flex-col md:flex-row items-start md:items-center justify-between gap-4 ${
                  alert.resolved ? "bg-slate-50/50 opacity-75" : "hover:bg-slate-50/80 bg-white"
                }`}
              >
                <div className="flex items-start gap-4">
                  <div
                    className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 mt-0.5 ${
                      alert.resolved
                        ? "bg-slate-100 text-slate-500"
                        : "bg-rose-50 text-rose-600 border border-rose-200"
                    }`}
                  >
                    <Flame className="w-5 h-5" />
                  </div>

                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-bold text-sm text-slate-900">
                        {alert.eventType || "GRIDLOCK_CONGESTION"}
                      </span>
                      <span className="inline-flex items-center gap-1 font-mono text-[11px] font-semibold bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md border border-slate-200">
                        <Video className="w-3 h-3 text-slate-500" />
                        {alert.cameraId || "CAM_01"}
                      </span>
                      {alert.reasoning && (
                        <span className="text-[11px] font-medium bg-rose-50 text-rose-700 border border-rose-200 px-2.5 py-0.5 rounded-md">
                          {alert.reasoning}
                        </span>
                      )}
                      {alert.resolved ? (
                        <span className="text-[10px] font-bold bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-md">
                          RESOLVED
                        </span>
                      ) : (
                        <span className="text-[10px] font-bold bg-rose-100 text-rose-700 px-2 py-0.5 rounded-md">
                          ACTIVE
                        </span>
                      )}
                    </div>

                    <div className="flex flex-wrap items-center gap-x-5 gap-y-1 mt-2 text-xs text-slate-500">
                      <span className="flex items-center gap-1">
                        <Car className="w-3.5 h-3.5 text-slate-400" />
                        <span className="font-semibold text-slate-700">{alert.vehicleCount || 0}</span> vehicles
                      </span>
                      <span>
                        Stopped / Crawling:{" "}
                        <span className="font-semibold text-rose-600">
                          {Math.round((alert.stationaryRatio || 0) * 100)}%
                        </span>
                      </span>
                      {alert.occupancyPercentage && (
                        <span>
                          Road Occupancy:{" "}
                          <span className="font-semibold text-amber-600">
                            {alert.occupancyPercentage}%
                          </span>
                        </span>
                      )}
                      <span className="flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5 text-slate-400" />
                        Duration: <span className="font-semibold text-slate-700">{alert.durationSec || 0}s</span>
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-end border-t md:border-t-0 pt-3 md:pt-0 border-slate-100">
                  <span className="font-mono text-xs text-slate-400">
                    {alert.createdAt ? new Date(alert.createdAt).toLocaleString() : "--:--"}
                  </span>
                  {!alert.resolved && (
                    <button
                      onClick={() => handleResolve(alert._id)}
                      className="px-3.5 py-1.5 text-xs font-semibold text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 rounded-lg shadow-sm transition-colors"
                    >
                      Acknowledge & Resolve
                    </button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}